---
title: "kamath_2022_ctrl"
author:
- name: Will Macnair
  affiliation: 
  - Computational Sciences Center of Excellence, F Hoffmann-La Roche Ltd, Basel, Switzerland
date: '`r format(as.Date("2026-03-23"), "%B %d, %Y")`'
output:
  rmdformats::downcute:
    highlight: textmate
    code_folding: hide
    toc_depth: 3
    css: custom.css
---


This page serves as a starting point for exploring the results of `scprocess`. The links below organize all generated reports, with each one detailing a specific step of the analysis (e.g., mapping, ambient RNA removal, QC).

Use this page to navigate through the full set of visualizations and outputs for your project.

## Core steps

- Mapping ([link](kamath_mapping.html))

- Ambient RNA removal ([link](kamath_ambient.html))
- QC ([link](kamath_qc.html))
- Highly variable genes ([link](kamath_hvgs.html))
- Integration ([link](kamath_integration.html))
- Marker genes ([link](kamath_marker_genes_0.2.html))

## Cell type annotation
- Celltype labelling ([link](kamath_label_celltypes.html))

## Subclustering
- da_neurons_0.2 ([link](kamath_zoom_da_neurons_0.2.html))

## Config files


<details closed>
<summary>▸ *config-kamath_2022_ctrl.yaml* (click to expand)</summary>

```yaml
project:
  proj_dir:         /pmount/projects/site/pred/brain-sc-data/kamath_2022_ctrl
  fastq_dir:        /pmount/projects/site/pred/brain-sc-analysis/studies/Kamath_2022_pos/data/fastqs
  full_tag:         kamath_2022_ctrl
  short_tag:        kamath
  your_name:        Will Macnair
  affiliation:      Computational Sciences Center of Excellence, F Hoffmann-La Roche Ltd, Basel, Switzerland
  sample_metadata:  data/metadata/sample_metadata_kamath_2022_ctrl_pos.csv
  ref_txome:        human_2024
  date_stamp:       "2026-03-23"
ambient:
  ambient_method:   cellbender
qc:
  qc_max_mito:      0.10
  qc_max_splice:    0.75
marker_genes:
  mkr_custom_genesets:
    - name: human_brain
label_celltypes:
  - labeller:       scprocess
    model:          human_cns
zoom:
  - data/metadata/zoom_params_kamath_2022_ctrl_dopaminergic.yaml
resources:
  retries:              2
  gb_save_alevin_to_h5: 16
  gb_run_cellbender:    32
```

</details>

<details closed>
<summary>▸ *zoom_params_kamath_2022_ctrl_dopaminergic.yaml* (click to expand)</summary>

```yaml
zoom:
  name:           da_neurons
  labels_source:  clusters
  sel_labels:     [cl02]
  labels_col:     RNA_snn_res.0.2
qc:
  qc_min_cells:   50
integration:
  int_n_dims:     20
```

</details>

